### PR TITLE
fix: use correct `Plugin` type import

### LINKED ISSUE #423: fix: Component types become any after router integration
### 🐛 The bug

Enable router integration
image

Disable router integration
image

### 🛠️ To reproduce

https://github.com/hawwei913/nuxt

### 🌈 Expected behaviour

Component types still preserve after enable route integration

### ℹ️ Additional context

no issue in [v0.8.1](https://github.com/nuxt-modules/ionic/releases/tag/0.8.1)

### PR DESCRIPTION
**Pull request by LouisHaftmann**
fixes #423

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
Thank you! ❤️

File: src/runtime/router.ts [hunk 1]
```diff
@@ -11,7 +11,8 @@ import type { RouteLocation, Router } from 'vue-router'
 import { createError } from 'h3'
 import { withoutBase, isEqual } from 'ufo'
 
-import type { PageMeta, RouteMiddleware, Plugin } from '#app'
+import type { PageMeta, RouteMiddleware } from '#app'
+import type { Plugin } from 'nuxt/app';
```
Comment (danielroe) [inline src/runtime/router.ts:15]:
```suggestion
import type { Plugin } from 'nuxt/app'
```

**Review by danielroe — APPROVED** [review]
